spring.application.name=cronograma-guardias
spring.datasource.url=jdbc:sqlite:guardias.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false
server.port=8080
spring.jackson.serialization.write-dates-as-timestamps=false
